{{- if .Values.istio.enabled }}
{{- if .Values.istio.rateLimit.enabled }}
---
# Rate limiting using Envoy filter
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: {{ include "security-patch-agent.fullname" . }}-ratelimit
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "security-patch-agent.labels" . | nindent 4 }}
spec:
  workloadSelector:
    labels:
      {{- include "security-patch-agent.selectorLabels" . | nindent 6 }}
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.local_ratelimit
        typed_config:
          "@type": type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
          value:
            stat_prefix: http_local_rate_limiter
            token_bucket:
              max_tokens: {{ .Values.istio.rateLimit.maxTokens }}
              tokens_per_fill: {{ .Values.istio.rateLimit.tokensPerFill }}
              fill_interval: {{ .Values.istio.rateLimit.fillInterval }}
            filter_enabled:
              runtime_key: local_rate_limit_enabled
              default_value:
                numerator: 100
                denominator: HUNDRED
            filter_enforced:
              runtime_key: local_rate_limit_enforced
              default_value:
                numerator: 100
                denominator: HUNDRED
            response_headers_to_add:
            - append: false
              header:
                key: x-local-rate-limit
                value: 'true'
{{- end }}
{{- end }}
