{{- if .Values.apiKeys.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "security-patch-agent.fullname" . }}-api-keys
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "security-patch-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-keys: {{ .Values.apiKeys.keys | join "," | quote }}
{{- end }}
