{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "security-patch-agent.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "security-patch-agent.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.workloadIdentity.enabled }}
    iam.gke.io/gcp-service-account: {{ .Values.workloadIdentity.gcpServiceAccount }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
